apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  namespace: ai-warehouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
      - name: jobmanager
        image: flink:1.18-scala_2.12
        args: ["jobmanager"]
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 8081
          name: ui
        env:
        - name: FLINK_PROPERTIES
          valueFrom:
            configMapKeyRef:
              name: flink-config
              key: flink-conf.yaml
        resources:
          requests:
            memory: "1.5Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
