apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
  namespace: ai-warehouse
data:
  flink-conf.yaml: |
    jobmanager.rpc.address: flink-jobmanager
    jobmanager.rpc.port: 6123
    jobmanager.memory.process.size: 1600m
    taskmanager.memory.process.size: 1728m
    taskmanager.numberOfTaskSlots: 2
    parallelism.default: 2
    state.backend: rocksdb
    state.checkpoints.dir: s3://warehouse/flink-checkpoints
    execution.checkpointing.interval: 60000
    execution.checkpointing.mode: EXACTLY_ONCE
