name: CD

on:
  push:
    branches: [main]
    tags: ["v*"]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Build Docker image
      run: docker build -t ai-warehouse/agent:${{ github.sha }} .
